-- Keep class ownership and student enrollment inside one active school.
-- These checks run for SQL, server, and Data API writes alike; the role in
-- school_memberships is authoritative, never user-controlled auth metadata.

create or replace function private.assert_class_teacher_membership()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1
    from public.school_memberships membership
    where membership.school_id = new.school_id
      and membership.user_id = new.teacher_id
      and membership.status = 'active'
      and membership.role in ('teacher', 'school_admin')
  ) then
    raise exception 'Class teacher must be an active teacher or administrator in the same school.';
  end if;
  return new;
end;
$$;

create or replace function private.assert_student_enrollment_membership()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  class_school_id uuid;
begin
  select school_id into class_school_id from public.classes where id = new.class_id;
  if class_school_id is null then
    raise exception 'Class does not exist.';
  end if;
  if not exists (
    select 1
    from public.school_memberships membership
    where membership.school_id = class_school_id
      and membership.user_id = new.student_id
      and membership.status = 'active'
      and membership.role = 'student'
  ) then
    raise exception 'Student must have an active student membership in the class school.';
  end if;
  return new;
end;
$$;

drop trigger if exists classes_validate_teacher_membership on public.classes;
create trigger classes_validate_teacher_membership
before insert or update of school_id, teacher_id on public.classes
for each row execute function private.assert_class_teacher_membership();

drop trigger if exists enrollments_validate_student_membership on public.enrollments;
create trigger enrollments_validate_student_membership
before insert or update of class_id, student_id on public.enrollments
for each row execute function private.assert_student_enrollment_membership();

revoke all on function private.assert_class_teacher_membership() from public, anon, authenticated;
revoke all on function private.assert_student_enrollment_membership() from public, anon, authenticated;

-- Teachers see only students in their own classes; students see their own
-- teachers. Administrators retain school-wide access.
create or replace function private.shares_class_context(target_user uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.is_admin()
    or exists (
      select 1
      from public.classes class_record
      join public.enrollments enrollment on enrollment.class_id = class_record.id
      where class_record.school_id = private.current_school_id()
        and class_record.teacher_id = (select auth.uid())
        and enrollment.student_id = target_user
    )
    or exists (
      select 1
      from public.classes class_record
      join public.enrollments my_enrollment on my_enrollment.class_id = class_record.id
      where class_record.school_id = private.current_school_id()
        and my_enrollment.student_id = (select auth.uid())
        and class_record.teacher_id = target_user
    )
$$;
revoke all on function private.shares_class_context(uuid) from public;
grant execute on function private.shares_class_context(uuid) to authenticated;

drop policy if exists "users view relevant profiles" on public.profiles;
create policy "class participants view relevant profiles" on public.profiles for select to authenticated using (
  id = (select auth.uid()) or private.shares_class_context(id)
);

drop policy if exists "staff and enrolled students view classes" on public.classes;
create policy "owners and enrolled students view classes" on public.classes for select to authenticated using (
  school_id = private.current_school_id()
  and (private.is_admin() or private.is_class_teacher(id) or private.is_enrolled(id))
);

create policy "students view assigned resources" on public.resources for select to authenticated using (
  exists (
    select 1 from public.resource_assignments assignment
    where assignment.resource_id = id and private.is_enrolled(assignment.class_id)
  )
);

-- A shareable code is separate from the internal UUID. It is generated by the
-- server for teachers and is the only class identifier students enter.
alter table public.classes add column if not exists join_code text;
update public.classes
set join_code = 'TM-' || upper(substr(encode(gen_random_bytes(6), 'hex'), 1, 12))
where join_code is null;
alter table public.classes alter column join_code set not null;
alter table public.classes drop constraint if exists classes_join_code_format;
alter table public.classes add constraint classes_join_code_format check (join_code ~ '^TM-[A-Z0-9]{8,16}$');
create unique index if not exists classes_join_code_unique_idx on public.classes(join_code);

-- Students may join only with a valid teacher-shared code, and only when they
-- already have an active student membership in that class's school.
create or replace function public.join_class_by_code(p_join_code text)
returns table (id uuid, name text, grade text, subject text, join_code text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_class public.classes%rowtype;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication is required.';
  end if;
  select * into target_class
  from public.classes
  where join_code = upper(trim(p_join_code));
  if not found then
    raise exception 'Class ID was not found.';
  end if;
  if not exists (
    select 1 from public.school_memberships membership
    where membership.school_id = target_class.school_id
      and membership.user_id = (select auth.uid())
      and membership.status = 'active'
      and membership.role = 'student'
  ) then
    raise exception 'Only active students in this school can join this class.';
  end if;
  insert into public.enrollments (class_id, student_id)
  values (target_class.id, (select auth.uid()))
  on conflict (class_id, student_id) do nothing;
  return query select target_class.id, target_class.name, target_class.grade, target_class.subject, target_class.join_code;
end;
$$;
revoke all on function public.join_class_by_code(text) from public, anon;
grant execute on function public.join_class_by_code(text) to authenticated;
